name: CI/CD Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Setup Docker Compose
      uses: docker/setup-qemu-action@v3
    
    - name: Ensure Docker Compose is available
      run: docker-compose version
    
    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Run integration tests
      run: ./scripts/run-integration.sh
