name : CI/CD Pipeline
on :
  push : 
    branches:
      - master
  pull_request :
    branches:
      - master
   
jobs:
  test :
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses : actions/checkout@v2

    - name : Setup docker 
      uses : docker/setup-buildx-action@v3
    
    - name : Setup Docker compose
      uses : docker/setup-qemu-action@v3
    
    - name : Ensure docker compose is avaialable
      run : docker-compose version
    
    - name : Copy .env.example to .env
      run : cp .env.example .env

    - name : Run integration tests 
      uses : ./scripts/run-integration.sh